## Aula 07 - Manipulação de Strings com Python 

>Uma variável primária de texto é chamada de char ou carcter possibilitando o armazenamento de 8 bit de memória. Quando necessitamos de um conjunto de caracteres utilizamos um objeto, ou variáveis compostas no caso da maioriria das linguagens chamada de string. Vamos ver como se aplica:

In [5]:
frase = "Boa tarde a todos"
print(frase)
saudacao = frase[0:9]
print(saudacao)


Boa tarde a todos
Boa tarde


In [6]:
print(type(frase))
print(type(saudacao))

<class 'str'>
<class 'str'>


In [7]:
print(frase.count(' '))
print(saudacao.count(' '))


3
1


In [8]:
print(len(frase))
print(len(saudacao))

17
9


In [9]:
frase = frase.replace('a todos',"galerinha")
print(frase)
saudacao = saudacao.replace('tarde' , 'noite')
print(saudacao)

Boa tarde galerinha
Boa noite


In [10]:
frase = [i for i in frase]
print(frase)

['B', 'o', 'a', ' ', 't', 'a', 'r', 'd', 'e', ' ', 'g', 'a', 'l', 'e', 'r', 'i', 'n', 'h', 'a']


## Exercício 1

>Crie um código para a seguinte frase: "Sabia que o sabiá sabia assubiar" reparticionado por espaços, após isso crie um print format para visualizar cada palavra em uma coluna separada.

In [55]:

frase = "sabia que o sabiá sabia assobiar"

palavras = frase.split()

for i in range(max(len(x)for x in palavras)):
    for y in palavras:
        print(y[i] if i < len(y) else ' ', end =' ')
    
    print()

s q o s s a 
a u   a a s 
b e   b b s 
i     i i o 
a     á a b 
          i 
          a 
          r 


In [53]:

for i in range(max(len(x) for x in palavras)):
    print(' '.join(x[i] if i< len(x) else ' ' for x in palavras))

s q o s s a
a u   a a s
b e   b b s
i     i i o
a     á a b
          i
          a
          r


## Introdução a Numpy


>Numpy é uma biblioteca python para desenvolvimento de matrizes. Tem por objetivos facilitar na criação de algoritmos matematicos para solucionar paradgimas avançados em relação a arrays.


In [25]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement as (from versions: none)
ERROR: No matching distribution found for as
You should consider upgrading via the 'c:\Users\gl401\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [38]:
import numpy as np
a = np.array([1,2,3])
print(a)


[1 2 3]


In [13]:
b = np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [14]:
c = np.ones((3,3))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
print(a.max())
print(b.max())
print(c.max())
print(d.max())

3
6
1.0
1.0


In [17]:
print(a.min())
print(b.min())
print(c.min())
print(d.min())

1
1
1.0
0.0


In [18]:
print(a.sum())
print(b.sum())
print(c.sum())
print(d.sum())

6
21
9.0
5.0


>Para calcular média

In [19]:
print(a.mean())
print(b.mean())
print(c.mean())
print(d.mean())

2.0
3.5
1.0
0.2


>Para desvio padrão

In [20]:
print(round(a.std(),2))
print(round(b.std(),2))
print(round(c.std(),2))
print(round(d.std(),2))

0.82
1.71
0.0
0.4


## Exercício 2

>Crie uma matriz chamada contar com os números de 0 até 9. Ao final crie uma contagem, média e desvio padrão dessa matriz. Para adicionar de zero a 9 utilize um for e depois atribua à matriz.

In [44]:
contar = np.array([])
for i in range (0,10,1):
    contar = np.append(contar,i)
print(contar)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [56]:
print("Contagem da matriz:")
print(contar)

print("\nMédia da matriz:")
print(contar.mean())

print("\nDesvio padrão da matriz:")
print(round(contar.std(),2))

Contagem da matriz:
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

Média da matriz:
4.5

Desvio padrão da matriz:
2.87
